# Generated by Django 4.2 on 2025-08-07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import registration.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalentEventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(
                    max_length=200, verbose_name='Full Name')),
                ('gender', models.CharField(choices=[
                 ('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.CharField(max_length=10,
                 verbose_name='Date of Birth (DD-MM-YYYY)')),
                ('age_group', models.CharField(choices=[('5-10', '5 Yrs to 10 Yrs'), ('11-20', '11 Yrs to 20 Yrs'), (
                    '21-40', '21 Yrs to 40 Yrs'), ('41-above', '41 Yrs and Above')], max_length=20, verbose_name='Age Group')),
                ('event', models.CharField(choices=[('singing', 'Singing'), ('dancing', 'Dancing'), (
                    'musical-instrument', 'Musical Instrument'), ('others', 'Others')], max_length=30, verbose_name='Event Category')),
                ('city', models.CharField(max_length=100,
                 verbose_name='Current Residence City')),
                ('whatsapp_number', models.CharField(
                    max_length=15, verbose_name='WhatsApp Number')),
                ('photo', models.ImageField(
                    upload_to=registration.models.participant_photo_path, verbose_name='Participant Photo')),
                ('terms', models.CharField(choices=[('yes', 'Yes, I Agree'), (
                    'no', "No, I Don't Agree")], max_length=5, verbose_name='Terms & Conditions Agreement')),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='Registration Date')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Last Updated')),
                ('is_active', models.BooleanField(
                    default=True, verbose_name='Is Active')),
                ('ip_address', models.GenericIPAddressField(
                    blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(
                    blank=True, null=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Talent Event Registration',
                'verbose_name_plural': 'Talent Event Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_registrations', models.IntegerField(default=0)),
                ('registrations_by_event', models.JSONField(default=dict)),
                ('registrations_by_age_group', models.JSONField(default=dict)),
                ('registrations_by_city', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Event Statistics',
                'verbose_name_plural': 'Event Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('registration', 'Registration Submitted'), ('photo_uploaded', 'Photo Uploaded'), (
                    'email_sent', 'Email Notification Sent'), ('video_submission', 'Video Submitted via WhatsApp'), ('status_update', 'Status Updated')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='activities', to='registration.talenteventregistration')),
            ],
            options={
                'verbose_name': 'Registration Activity',
                'verbose_name_plural': 'Registration Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='talenteventregistration',
            index=models.Index(fields=['created_at'],
                               name='registratio_created_4b2e85_idx'),
        ),
        migrations.AddIndex(
            model_name='talenteventregistration',
            index=models.Index(
                fields=['event'], name='registratio_event_5e4e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='talenteventregistration',
            index=models.Index(fields=['age_group'],
                               name='registratio_age_gro_df6e98_idx'),
        ),
        migrations.AddIndex(
            model_name='talenteventregistration',
            index=models.Index(
                fields=['city'], name='registratio_city_c0b37e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventstatistics',
            unique_together={('date',)},
        ),
    ]
