# Generated by Django 4.2.16 on 2025-08-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="talenteventregistration",
            new_name="registratio_created_643444_idx",
            old_name="registratio_created_4b2e85_idx",
        ),
        migrations.RenameIndex(
            model_name="talenteventregistration",
            new_name="registratio_event_be6e1d_idx",
            old_name="registratio_event_5e4e2e_idx",
        ),
        migrations.RenameIndex(
            model_name="talenteventregistration",
            new_name="registratio_age_gro_84d612_idx",
            old_name="registratio_age_gro_df6e98_idx",
        ),
        migrations.RenameIndex(
            model_name="talenteventregistration",
            new_name="registratio_city_09794b_idx",
            old_name="registratio_city_c0b37e_idx",
        ),
    ]
