# Generated by Django 4.2.16 on 2025-08-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0002_rename_registratio_created_4b2e85_idx_registratio_created_643444_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="talenteventregistration",
            options={
                "ordering": ["serial_number"],
                "verbose_name": "Talent Event Registration",
                "verbose_name_plural": "Talent Event Registrations",
            },
        ),
        migrations.AddField(
            model_name="talenteventregistration",
            name="serial_number",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Serial Number",
            ),
        ),
        migrations.AddIndex(
            model_name="talenteventregistration",
            index=models.Index(
                fields=["serial_number"], name="registratio_serial__840ecd_idx"
            ),
        ),
    ]
