# Generated by Django 4.2.16 on 2025-08-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_alter_talenteventregistration_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="talenteventregistration",
            index=models.Index(
                fields=["full_name", "whatsapp_number"],
                name="registratio_full_na_7808d0_idx",
            ),
        ),
    ]
