# Generated by Django 4.2.9 on 2025-08-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_talenteventregistration_registratio_full_na_7808d0_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name='talenteventregistration',
            name='talent_details',
            field=models.TextField(
                max_length=500,
                verbose_name='Talent Details',
                help_text='Details about talent (instruments, awards, shows, etc.)'
            ),
        ),
    ]
